before_install:
  - travis_retry sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ hardy universe"
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install gcc-3.3
  - gcc --version
